<?php

/**
 * @file
 * Contains decoupled_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function decoupled_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the decoupled_block module.
    case 'help.page.decoupled_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Get the block using the drupal APIs and return the JSON response') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function decoupled_block_theme() {
  return [
    'decoupled_block' => [
      'render element' => 'children',
    ],
  ];
}
